spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8081
            predicates:
              - Path= /api/v1/customers/**
          - id: r2
            uri: http://localhost:8082
            predicates:
              - Path= /api/v1/products /**
                      
